**TITANIC DATASET PROCESSING**

In [1]:
#Creating DataFrame
import pandas as pd
df=pd.read_csv('titanic.csv')
print(df.head(5))

                                            Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female
1                    Allison, Miss Helen Loraine    1st   2.00  female
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female
4                  Allison, Master Hudson Trevor    1st   0.92    male

   Survived  SexCode
0         1        1
1         0        1
2         0        0
3         0        1
4         1        0

In [2]:
#Creating Sample DataFrame
import pandas as pd
sample=pd.DataFrame()
sample['Name']=['Mahesh','Kacham']
sample['Age']=[26,24]
sample['Gender']=['Male','Male']

print(sample)

     Name  Age Gender
0  Mahesh   26   Male
1  Kacham   24   Male

In [3]:
#Number of Rows and Columns
import pandas as pd
df=pd.read_csv('titanic.csv')
df.shape

(1313, 6)

In [4]:
# Describing the DataFrame
df.describe()

              Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [5]:
#Craeting DataFrame: Accessing the First Row
import pandas as pd
df=pd.read_csv('titanic.csv')

print(df.iloc[(0)])

Name        Allen, Miss Elisabeth Walton
PClass                               1st
Age                                 29.0
Sex                               female
Survived                               1
SexCode                                1
Name: 0, dtype: object

In [6]:
 #Selecting Multiple Rows
 import pandas as pd
 df=pd.read_csv('titanic.csv')
 df.iloc[0:9]

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0
5,"Anderson, Mr Harry",1st,47.00,male,1,0
6,"Andrews, Miss Kornelia Theodosia",1st,63.00,female,1,1
7,"Andrews, Mr Thomas, jr",1st,39.00,male,0,0
8,"Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58.00,female,1,1

In [7]:
# Setting Name column as index
import pandas as pd
df = pd.read_csv('titanic.csv')
df = df.set_index(df['Name'])
(df.head())

,Name,PClass,Age,Sex,Survived,SexCode
Name,,,,,,
"Allen, Miss Elisabeth Walton","Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
"Allison, Miss Helen Loraine","Allison, Miss Helen Loraine",1st,2.00,female,0,1
"Allison, Mr Hudson Joshua Creighton","Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
"Allison, Mrs Hudson JC (Bessie Waldo Daniels)","Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
"Allison, Master Hudson Trevor","Allison, Master Hudson Trevor",1st,0.92,male,1,0

# **Output Display in Colab Without print()**

In [8]:
#Accessing First Row after setting name column as Index
import pandas as pd
df=pd.read_csv('titanic.csv')
df=df.set_index(df['Name'])
df.loc['Allen, Miss Elisabeth Walton']

Name        Allen, Miss Elisabeth Walton
PClass                               1st
Age                                 29.0
Sex                               female
Survived                               1
SexCode                                1
Name: Allen, Miss Elisabeth Walton, dtype: object

In [9]:
#Selecting Rows based on Condition
import pandas as pd
df=pd.read_csv('titanic.csv')
df1=df[df['Sex']=='male']
df1.head()

                                  Name PClass    Age   Sex  Survived  SexCode
2  Allison, Mr Hudson Joshua Creighton    1st  30.00  male         0        0
4        Allison, Master Hudson Trevor    1st   0.92  male         1        0
5                   Anderson, Mr Harry    1st  47.00  male         1        0
7               Andrews, Mr Thomas, jr    1st  39.00  male         0        0
9               Artagaveytia, Mr Ramon    1st  71.00  male         0        0

In [10]:
# Selecting Rows based on Condition
import pandas as pd
df=pd.read_csv('titanic.csv')
df1 = df[(df['Sex']== 'female') & (df['Age']>=65)]
df1.head()

,Name,PClass,Age,Sex,Survived,SexCode
73,"Crosby, Mrs Edward Gifford (Catherine Elizabet...",1st,69.0,female,1,1

In [11]:
#Replacing Values
import pandas as pd
df=pd.read_csv('titanic.csv')
df1=df['Sex'].replace('female','Woman')
print(df1.head())

0    Woman
1    Woman
2     male
3    Woman
4     male
Name: Sex, dtype: object

In [12]:
#Replacing Values
import pandas as pd
df=pd.read_csv('titanic.csv')
df1=df['Sex'].replace(['female','male'],['Woman','man'])
print(df1.head())

0    Woman
1    Woman
2      man
3    Woman
4      man
Name: Sex, dtype: object

In [13]:
#Replacing Values
df1=df.replace(1,'one')
df1.head()

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.0,female,one,one
1,"Allison, Miss Helen Loraine",1st,2.0,female,0,one
2,"Allison, Mr Hudson Joshua Creighton",1st,30.0,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.0,female,0,one
4,"Allison, Master Hudson Trevor",1st,0.92,male,one,0

In [14]:
#Replacing Values
df1=df.replace('1st','First',regex=True)
df1.head()

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",First,29.00,female,1,1
1,"Allison, Miss Helen Loraine",First,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",First,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",First,25.00,female,0,1
4,"Allison, Master Hudson Trevor",First,0.92,male,1,0

In [15]:
#Renaming Column Values
df1=df.rename(columns={'PClass':'Passenger Class','Sex':'Gender'})
df1.head()

,Name,Passenger Class,Age,Gender,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0

In [16]:
# Find mean,max,min,sum,count of Age Column
print(df['Age'].max())
print(df['Age'].min())
print(df['Age'].sum())
print(df['Age'].mean())
df['Age'].count()

71.0
0.17
22980.88
30.397989417989418

np.int64(756)

In [17]:
#Count of Each Column
import pandas as pd
df=pd.read_csv('titanic.csv')
df.count()

Name        1313
PClass      1313
Age          756
Sex         1313
Survived    1313
SexCode     1313
dtype: int64

In [18]:
#Unique value in Column
import pandas as pd
df=pd.read_csv('titanic.csv')
df['Sex'].unique()

array(['female', 'male'], dtype=object)

In [19]:
#Count of each value in Sex column
import pandas as pd
df = pd.read_csv('titanic.csv')
df['Sex'].value_counts()

Sex
male      851
female    462
Name: count, dtype: int64

In [20]:
#Count of each value in Sex column
import pandas as pd
df=pd.read_csv('titanic.csv')
df['PClass'].value_counts()

PClass
3rd    711
1st    322
2nd    279
*        1
Name: count, dtype: int64

In [21]:
#Unique values in PClass column

import pandas as pd
df = pd.read_csv('titanic.csv')
df['PClass'].nunique()

4

In [22]:
# Checking null Values
import pandas as pd
df = pd.read_csv('titanic.csv')
df[df['Age'].isnull()]

                              Name PClass  Age     Sex  Survived  SexCode
12    Aubert, Mrs Leontine Pauline    1st  NaN  female         1        1
13        Barkworth, Mr Algernon H    1st  NaN    male         1        0
14              Baumann, Mr John D    1st  NaN    male         0        0
29         Borebank, Mr John James    1st  NaN    male         0        0
32              Bradley, Mr George    1st  NaN    male         1        0
...                            ...    ...  ...     ...       ...      ...
1300         Wiseman, Mr Phillippe    3rd  NaN    male         0        0
1302             Yalsevac, Mr Ivan    3rd  NaN    male         1        0
1305            Youssef, Mr Gerios    3rd  NaN    male         0        0
1306           Zabour, Miss Hileni    3rd  NaN  female         0        1
1307           Zabour, Miss Tamini    3rd  NaN  female         0        1

[557 rows x 6 columns]

In [23]:
#Dropping the Column
import pandas as pd
df = pd.read_csv('titanic.csv')
df.drop('Age', axis = 1)

,Name,PClass,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,female,1,1
1,"Allison, Miss Helen Loraine",1st,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,female,0,1
4,"Allison, Master Hudson Trevor",1st,male,1,0
...,...,...,...,...,...
1308,"Zakarian, Mr Artun",3rd,male,0,0
1309,"Zakarian, Mr Maprieder",3rd,male,0,0
1310,"Zenni, Mr Philip",3rd,male,0,0
1311,"Lievens, Mr Rene",3rd,male,0,0
1312,"Zimmerman, Leo",3rd,male,0,0

In [24]:
#Dropping the Columns
import pandas as pd
df = pd.read_csv('titanic.csv')
df.drop(['Age', 'Sex'], axis=1).head(10)

                                            Name PClass  Survived  SexCode
0                   Allen, Miss Elisabeth Walton    1st         1        1
1                    Allison, Miss Helen Loraine    1st         0        1
2            Allison, Mr Hudson Joshua Creighton    1st         0        0
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st         0        1
4                  Allison, Master Hudson Trevor    1st         1        0
5                             Anderson, Mr Harry    1st         1        0
6               Andrews, Miss Kornelia Theodosia    1st         1        1
7                         Andrews, Mr Thomas, jr    1st         0        0
8   Appleton, Mrs Edward Dale (Charlotte Lamson)    1st         1        1
9                         Artagaveytia, Mr Ramon    1st         0        0

In [25]:
#Selecting DataFrame based on condition
import pandas as pd
df = pd.read_csv('titanic.csv')
df[df['Sex']!='male'].head()

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.0,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.0,female,0,1
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.0,female,0,1
6,"Andrews, Miss Kornelia Theodosia",1st,63.0,female,1,1
8,"Appleton, Mrs Edward Dale (Charlotte Lamson)",1st,58.0,female,1,1

In [26]:
#Selecting DataFrame based on condition

import pandas as pd
df = pd.read_csv('titanic.csv')
df[df.index != 0].head()

,Name,PClass,Age,Sex,Survived,SexCode
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0
5,"Anderson, Mr Harry",1st,47.00,male,1,0

In [27]:
#Using Groupby
import pandas as pd
df = pd.read_csv('titanic.csv')
df.groupby('Sex').mean(numeric_only=True)

              Age  Survived  SexCode
Sex
female  29.396424  0.666667      1.0
male    31.014338  0.166863      0.0